### PR TITLE
Update example to v1.8.0

### PR DESCRIPTION
**Pull request by SandyEma9**

### CODE REVIEW

**Review by iulianatodoran — APPROVED** [review]
Checked running the script for tests locally and everything is ok. LGTM.

**Comment by SandyEma9** [comment]
@robert-altom @RobertPoienar @gomboskriszta15 @ReichEdvin

**Comment by robert-altom** [comment]
It look like there are a lot of `*.log` files and `.DS_Store` files, you should remove them.

Also add a `.gitignore` file for Java: 

```
# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files #
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml
hs_err_pid*
```

**Comment by rucindrea** [comment]
LGTM.

**Pull request merged**
